package tj.rustam.englishtajik;

import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.widget.EditText;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    List<String[]> allWords = new ArrayList<>();
    WordAdapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        loadAllWords();

        RecyclerView rv = findViewById(R.id.recyclerView);
        EditText search = findViewById(R.id.searchEdit);
        adapter = new WordAdapter(allWords);
        rv.setLayoutManager(new LinearLayoutManager(this));
        rv.setAdapter(adapter);
        search.addTextChangedListener(new TextWatcher() {
            public void beforeTextChanged(CharSequence s,int a,int b,int c){}
            public void onTextChanged(CharSequence s,int a,int b,int c){
                String q = s.toString().toLowerCase().trim();
                List<String[]> filtered = new ArrayList<>();
                if(q.isEmpty()) filtered = allWords;
                else {
                    for(String[] w: allWords){
                        if(w[0].toLowerCase().contains(q) || w[1].toLowerCase().contains(q)) filtered.add(w);
                    }
                }
                adapter.update(filtered);
            }
            public void afterTextChanged(Editable s){}
        });
    }

    private void loadAllWords(){
        loadPart1();
        loadPart2();
        loadPart3();
    }

    private void loadPart1(){
allWords.add(new String[]{"hello","салом"});
allWords.add(new String[]{"goodbye","хайр"});
allWords.add(new String[]{"thank you","ташаккур"});
allWords.add(new String[]{"please","марҳамат"});
allWords.add(new String[]{"yes","ҳа"});
allWords.add(new String[]{"no","не"});
allWords.add(new String[]{"water","об"});
allWords.add(new String[]{"bread","нон"});
allWords.add(new String[]{"book","китоб"});
allWords.add(new String[]{"school","мактаб"});
allWords.add(new String[]{"teacher","омӯзгор"});
allWords.add(new String[]{"student","хонанда"});
allWords.add(new String[]{"friend","дӯст"});
allWords.add(new String[]{"family","оила"});
allWords.add(new String[]{"mother","модар"});
allWords.add(new String[]{"father","падар"});
allWords.add(new String[]{"house","хона"});
allWords.add(new String[]{"time","вақт"});
allWords.add(new String[]{"day","рӯз"});
allWords.add(new String[]{"night","шаб"});
allWords.add(new String[]{"love","ишқ"});
allWords.add(new String[]{"work","кор"});
allWords.add(new String[]{"life","ҳаёт"});
allWords.add(new String[]{"world","ҷаҳон"});
allWords.add(new String[]{"food","хӯрок"});
allWords.add(new String[]{"city","шаҳр"});
allWords.add(new String[]{"language","забон"});
allWords.add(new String[]{"learn","омӯхтан"});
allWords.add(new String[]{"today","имрӯз"});
allWords.add(new String[]{"money","пул"});
allWords.add(new String[]{"market","бозор"});
allWords.add(new String[]{"tea","чой"});
allWords.add(new String[]{"airport","фурудгоҳ"});
allWords.add(new String[]{"dictionary","луғат"});
allWords.add(new String[]{"about","дар бораи"});
allWords.add(new String[]{"above","боло"});
allWords.add(new String[]{"action","амал"});
allWords.add(new String[]{"activity","фаъолият"});
allWords.add(new String[]{"address","суроға"});
allWords.add(new String[]{"after","баъд"});
allWords.add(new String[]{"again","боз"});
allWords.add(new String[]{"against","зидди"});
allWords.add(new String[]{"age","синну сол"});
allWords.add(new String[]{"air","ҳаво"});
allWords.add(new String[]{"all","ҳама"});
allWords.add(new String[]{"allow","иҷозат додан"});
allWords.add(new String[]{"almost","қариб"});
allWords.add(new String[]{"alone","танҳо"});
allWords.add(new String[]{"along","дар баробари"});
allWords.add(new String[]{"already","аллакай"});
allWords.add(new String[]{"also","ҳамчунин"});
allWords.add(new String[]{"always","ҳамеша"});
allWords.add(new String[]{"among","байни"});
allWords.add(new String[]{"amount","маблағ"});
allWords.add(new String[]{"animal","ҳайвон"});
allWords.add(new String[]{"another","дигар"});
allWords.add(new String[]{"answer","ҷавоб"});
allWords.add(new String[]{"any","ҳар"});
allWords.add(new String[]{"appear","пайдо шудан"});
allWords.add(new String[]{"area","минтақа"});
allWords.add(new String[]{"arm","даст"});
allWords.add(new String[]{"around","атроф"});
allWords.add(new String[]{"ask","пурсидан"});
allWords.add(new String[]{"baby","кӯдак"});
allWords.add(new String[]{"back","пушт"});
allWords.add(new String[]{"bag","халта"});
allWords.add(new String[]{"ball","тӯб"});
allWords.add(new String[]{"bank","бонк"});
allWords.add(new String[]{"base","асос"});
allWords.add(new String[]{"be","будан"});
allWords.add(new String[]{"because","зеро"});
allWords.add(new String[]{"become","шудан"});
allWords.add(new String[]{"bed","кат"});
allWords.add(new String[]{"before","пеш"});
allWords.add(new String[]{"begin","оғоз кардан"});
allWords.add(new String[]{"behind","паси"});
allWords.add(new String[]{"believe","бовар кардан"});
allWords.add(new String[]{"below","поён"});
allWords.add(new String[]{"best","беҳтарин"});
allWords.add(new String[]{"better","беҳтар"});
allWords.add(new String[]{"between","байни"});
allWords.add(new String[]{"bird","парранда"});
allWords.add(new String[]{"black","сиёҳ"});
allWords.add(new String[]{"blue","кабуд"});
allWords.add(new String[]{"boat","қаиқ"});
allWords.add(new String[]{"body","бадан"});
allWords.add(new String[]{"both","ҳар ду"});
allWords.add(new String[]{"box","қуттӣ"});
allWords.add(new String[]{"boy","писар"});
allWords.add(new String[]{"break","шикастан"});
allWords.add(new String[]{"bring","овардан"});
allWords.add(new String[]{"brother","бародар"});
allWords.add(new String[]{"build","сохтан"});
allWords.add(new String[]{"business","тиҷорат"});
allWords.add(new String[]{"but","аммо"});
allWords.add(new String[]{"buy","харидан"});
allWords.add(new String[]{"call","занг задан"});
allWords.add(new String[]{"can","метавонам"});
allWords.add(new String[]{"care","ғамхорӣ"});
allWords.add(new String[]{"case","ҳолат"});
allWords.add(new String[]{"catch","доштан"});
allWords.add(new String[]{"cause","сабаб"});
allWords.add(new String[]{"center","марказ"});
allWords.add(new String[]{"chair","курсӣ"});
allWords.add(new String[]{"change","тағйир"});
allWords.add(new String[]{"check","санҷидан"});
allWords.add(new String[]{"class","синф"});
allWords.add(new String[]{"clean","тоза"});
allWords.add(new String[]{"clear","равшан"});
allWords.add(new String[]{"close","наздик"});
allWords.add(new String[]{"cold","сард"});
allWords.add(new String[]{"color","ранг"});
allWords.add(new String[]{"come","омадан"});
allWords.add(new String[]{"common","умумӣ"});
allWords.add(new String[]{"company","ширкат"});
allWords.add(new String[]{"control","назорат"});
allWords.add(new String[]{"cost","арзиш"});
allWords.add(new String[]{"country","кишвар"});
allWords.add(new String[]{"course","курс"});
allWords.add(new String[]{"cover","пӯшиш"});
allWords.add(new String[]{"create","эҷод кардан"});
allWords.add(new String[]{"culture","фарҳанг"});
allWords.add(new String[]{"cup","пиёла"});
allWords.add(new String[]{"cut","буридан"});
allWords.add(new String[]{"dance","рақс"});
allWords.add(new String[]{"dark","торик"});
allWords.add(new String[]{"day","рӯз"});
allWords.add(new String[]{"dead","мурда"});
allWords.add(new String[]{"deep","чуқур"});
allWords.add(new String[]{"different","гуногун"});
allWords.add(new String[]{"difficult","душвор"});
allWords.add(new String[]{"do","кардан"});
allWords.add(new String[]{"doctor","духтур"});
allWords.add(new String[]{"dog","саг"});
allWords.add(new String[]{"door","дар"});
allWords.add(new String[]{"down","поён"});
allWords.add(new String[]{"draw","кашидан"});
allWords.add(new String[]{"dream","орзу"});
allWords.add(new String[]{"dress","либос"});
allWords.add(new String[]{"drink","нӯшидан"});
allWords.add(new String[]{"drive","рондан"});
allWords.add(new String[]{"early","барвақт"});
allWords.add(new String[]{"earth","замин"});
allWords.add(new String[]{"easy","осон"});
allWords.add(new String[]{"eat","хӯрдан"});
allWords.add(new String[]{"education","таҳсилот"});
allWords.add(new String[]{"effect","таъсир"});
allWords.add(new String[]{"eight","ҳашт"});
allWords.add(new String[]{"end","охир"});
allWords.add(new String[]{"energy","энергия"});
allWords.add(new String[]{"enough","кофӣ"});
allWords.add(new String[]{"even","ҳатто"});
allWords.add(new String[]{"evening","бегоҳ"});
allWords.add(new String[]{"every","ҳар"});
allWords.add(new String[]{"eye","чашм"});
allWords.add(new String[]{"face","чеҳра"});
allWords.add(new String[]{"far","дур"});
allWords.add(new String[]{"fast","тез"});
allWords.add(new String[]{"feel","ҳис кардан"});
allWords.add(new String[]{"few","кам"});
allWords.add(new String[]{"find","ёфтан"});
allWords.add(new String[]{"fire","оташ"});
allWords.add(new String[]{"first","аввал"});
allWords.add(new String[]{"fish","моҳӣ"});
allWords.add(new String[]{"five","панҷ"});
allWords.add(new String[]{"flower","гул"});
allWords.add(new String[]{"foot","по"});
allWords.add(new String[]{"for","барои"});
allWords.add(new String[]{"four","чор"});
allWords.add(new String[]{"free","озод"});
allWords.add(new String[]{"from","аз"});
allWords.add(new String[]{"game","бозӣ"});
allWords.add(new String[]{"garden","боғ"});
allWords.add(new String[]{"get","гирифтан"});
allWords.add(new String[]{"girl","духтар"});
allWords.add(new String[]{"give","додан"});
allWords.add(new String[]{"go","рафтан"});
allWords.add(new String[]{"good","хуб"});
allWords.add(new String[]{"great","бузург"});
allWords.add(new String[]{"green","сабз"});
allWords.add(new String[]{"hand","даст"});
allWords.add(new String[]{"happy","хушбахт"});
allWords.add(new String[]{"have","доштан"});
allWords.add(new String[]{"he","ӯ"});
allWords.add(new String[]{"head","сар"});
allWords.add(new String[]{"health","саломатӣ"});
allWords.add(new String[]{"hear","шунидан"});
allWords.add(new String[]{"heart","дил"});
allWords.add(new String[]{"help","кӯмак"});
allWords.add(new String[]{"home","хона"});
allWords.add(new String[]{"hope","умед"});
allWords.add(new String[]{"how","чигуна"});
allWords.add(new String[]{"idea","ғоя"});
allWords.add(new String[]{"important","муҳим"});
allWords.add(new String[]{"in","дар"});
allWords.add(new String[]{"job","кор"});
allWords.add(new String[]{"keep","нигоҳ доштан"});
allWords.add(new String[]{"key","калид"});
allWords.add(new String[]{"know","донистан"});
allWords.add(new String[]{"large","калон"});
allWords.add(new String[]{"last","охирин"});
allWords.add(new String[]{"life","ҳаёт"});
allWords.add(new String[]{"light","нур"});
allWords.add(new String[]{"like","монанди"});
allWords.add(new String[]{"little","хурд"});
allWords.add(new String[]{"live","зиндагӣ кардан"});
allWords.add(new String[]{"long","дароз"});
allWords.add(new String[]{"look","нигоҳ кардан"});
allWords.add(new String[]{"love","ишқ"});
allWords.add(new String[]{"make","сохтан"});
allWords.add(new String[]{"man","мард"});
allWords.add(new String[]{"many","бисёр"});
allWords.add(new String[]{"more","бештар"});
allWords.add(new String[]{"morning","субҳ"});
allWords.add(new String[]{"mother","модар"});
allWords.add(new String[]{"much","бисёр"});
allWords.add(new String[]{"music","мусиқӣ"});
allWords.add(new String[]{"name","ном"});
allWords.add(new String[]{"need","ниёз"});
allWords.add(new String[]{"new","нав"});
allWords.add(new String[]{"night","шаб"});
allWords.add(new String[]{"no","не"});
allWords.add(new String[]{"now","ҳозир"});
allWords.add(new String[]{"old","кӯҳна"});
allWords.add(new String[]{"one","як"});
allWords.add(new String[]{"only","танҳо"});
allWords.add(new String[]{"open","кушодан"});
allWords.add(new String[]{"other","дигар"});
allWords.add(new String[]{"our","мо"});
allWords.add(new String[]{"out","берун"});
allWords.add(new String[]{"over","боло"});
allWords.add(new String[]{"people","мардум"});
allWords.add(new String[]{"person","шахс"});
allWords.add(new String[]{"phone","телефон"});
allWords.add(new String[]{"place","ҷой"});
allWords.add(new String[]{"please","марҳамат"});
allWords.add(new String[]{"poor","камбағал"});
allWords.add(new String[]{"possible","мумкин"});
allWords.add(new String[]{"question","савол"});
allWords.add(new String[]{"read","хондан"});
allWords.add(new String[]{"right","рост"});
allWords.add(new String[]{"road","роҳ"});
allWords.add(new String[]{"school","мактаб"});
allWords.add(new String[]{"see","дидан"});
allWords.add(new String[]{"small","хурд"});
allWords.add(new String[]{"speak","гап задан"});
allWords.add(new String[]{"student","донишҷӯ"});
allWords.add(new String[]{"table","миз"});
allWords.add(new String[]{"take","гирифтан"});
allWords.add(new String[]{"talk","суҳбат"});
allWords.add(new String[]{"teach","омӯзондан"});
allWords.add(new String[]{"thank you","ташаккур"});
allWords.add(new String[]{"time","вақт"});
allWords.add(new String[]{"today","имрӯз"});
allWords.add(new String[]{"tomorrow","фардо"});
allWords.add(new String[]{"understand","фаҳмидан"});
allWords.add(new String[]{"water","об"});
allWords.add(new String[]{"way","роҳ"});
allWords.add(new String[]{"we","мо"});
allWords.add(new String[]{"what","чӣ"});
allWords.add(new String[]{"when","кай"});
allWords.add(new String[]{"where","куҷо"});
allWords.add(new String[]{"who","кӣ"});
allWords.add(new String[]{"why","чаро"});
allWords.add(new String[]{"woman","зан"});
allWords.add(new String[]{"word","калима"});
allWords.add(new String[]{"work","кор"});
allWords.add(new String[]{"world","ҷаҳон"});
allWords.add(new String[]{"write","навиштан"});
allWords.add(new String[]{"year","сол"});
allWords.add(new String[]{"yes","ҳа"});
allWords.add(new String[]{"you","ту"});
    }

    private void loadPart2(){
allWords.add(new String[]{"abnormal","ғайримуқаррарӣ"});
allWords.add(new String[]{"absolute","мутлақ"});
allWords.add(new String[]{"accident","садама"});
allWords.add(new String[]{"accuracy","дақиқӣ"});
allWords.add(new String[]{"activate","фаъол кардан"});
allWords.add(new String[]{"addition","илова"});
allWords.add(new String[]{"adequate","кифоя"});
allWords.add(new String[]{"alphabet","алифбо"});
allWords.add(new String[]{"anything","чизе"});
allWords.add(new String[]{"anywhere","дар ҳама ҷо"});
allWords.add(new String[]{"approach","равиш"});
allWords.add(new String[]{"approval","тасдиқ"});
allWords.add(new String[]{"argument","баҳс"});
allWords.add(new String[]{"attitude","муносибат"});
allWords.add(new String[]{"audience","тамошобинон"});
allWords.add(new String[]{"backward","ақиб"});
allWords.add(new String[]{"birthday","таваллуд"});
allWords.add(new String[]{"building","бино"});
allWords.add(new String[]{"campaign","маърака"});
allWords.add(new String[]{"children","кӯдакон"});
allWords.add(new String[]{"complete","пурра"});
allWords.add(new String[]{"consider","баррасӣ кардан"});
allWords.add(new String[]{"continue","давом додан"});
allWords.add(new String[]{"daughter","духтар"});
allWords.add(new String[]{"decision","қарор"});
allWords.add(new String[]{"describe","тавсиф кардан"});
allWords.add(new String[]{"economic","иқтисодӣ"});
allWords.add(new String[]{"elephant","фил"});
allWords.add(new String[]{"employee","коргар"});
allWords.add(new String[]{"entrance","даромадгоҳ"});
allWords.add(new String[]{"exercise","машқ кардан"});
allWords.add(new String[]{"festival","фестивал"});
allWords.add(new String[]{"generate","тавлид"});
allWords.add(new String[]{"greeting","салом"});
allWords.add(new String[]{"hospital","беморхона"});
allWords.add(new String[]{"imagine","тасаввур кардан"});
allWords.add(new String[]{"important","муҳим"});
allWords.add(new String[]{"improve","беҳтар кардан"});
allWords.add(new String[]{"include","дохил кардан"});
allWords.add(new String[]{"increase","зиёд кардан"});
allWords.add(new String[]{"industry","саноат"});
allWords.add(new String[]{"information","маълумот"});
allWords.add(new String[]{"inside","дар дохил"});
allWords.add(new String[]{"instead","ба ҷои"});
allWords.add(new String[]{"interest","таваҷҷӯҳ"});
allWords.add(new String[]{"internet","интернет"});
allWords.add(new String[]{"interview","мусоҳиба"});
allWords.add(new String[]{"introduce","муаррифӣ кардан"});
allWords.add(new String[]{"invite","даъват кардан"});
allWords.add(new String[]{"island","ҷазира"});
allWords.add(new String[]{"issue","масъала"});
allWords.add(new String[]{"jacket","курта"});
allWords.add(new String[]{"journey","сафар"});
allWords.add(new String[]{"judge","қозӣ"});
allWords.add(new String[]{"juice","шарбат"});
allWords.add(new String[]{"jump","ҷаҳидан"});
allWords.add(new String[]{"just","танҳо"});
allWords.add(new String[]{"kitchen","ошхона"});
allWords.add(new String[]{"knowledge","дониш"});
allWords.add(new String[]{"laugh","хандидан"});
allWords.add(new String[]{"lawyer","ҳуқуқшинос"});
allWords.add(new String[]{"leader","роҳбар"});
allWords.add(new String[]{"lesson","дарс"});
allWords.add(new String[]{"letter","мактуб"});
allWords.add(new String[]{"level","сатҳ"});
allWords.add(new String[]{"library","китобхона"});
allWords.add(new String[]{"license","иҷозатнома"});
allWords.add(new String[]{"listen","гӯш кардан"});
allWords.add(new String[]{"manage","идора кардан"});
allWords.add(new String[]{"manager","менеҷер"});
allWords.add(new String[]{"marriage","издивоҷ"});
allWords.add(new String[]{"material","мавод"});
allWords.add(new String[]{"measure","чен кардан"});
allWords.add(new String[]{"meeting","вохӯрӣ"});
allWords.add(new String[]{"member","аъзо"});
allWords.add(new String[]{"message","паём"});
allWords.add(new String[]{"method","усул"});
allWords.add(new String[]{"middle","миёна"});
allWords.add(new String[]{"minute","дақиқа"});
allWords.add(new String[]{"mistake","хато"});
allWords.add(new String[]{"modern","муосир"});
allWords.add(new String[]{"moment","лаҳза"});
allWords.add(new String[]{"month","моҳ"});
allWords.add(new String[]{"mountain","кӯҳ"});
allWords.add(new String[]{"mouth","даҳон"});
allWords.add(new String[]{"move","ҳаракат кардан"});
allWords.add(new String[]{"movie","филм"});
allWords.add(new String[]{"national","миллӣ"});
allWords.add(new String[]{"nature","табиат"});
allWords.add(new String[]{"necessary","зарур"});
allWords.add(new String[]{"never","ҳеҷ гоҳ"});
allWords.add(new String[]{"newspaper","рӯзнома"});
allWords.add(new String[]{"next","оянда"});
allWords.add(new String[]{"nice","хуб"});
allWords.add(new String[]{"north","шимол"});
allWords.add(new String[]{"note","ёддошт"});
allWords.add(new String[]{"nothing","ҳеҷ чиз"});
allWords.add(new String[]{"notice","огоҳӣ"});
allWords.add(new String[]{"number","рақам"});
allWords.add(new String[]{"object","ашё"});
allWords.add(new String[]{"offer","пешниҳод"});
allWords.add(new String[]{"office","идора"});
allWords.add(new String[]{"often","аксар вақт"});
allWords.add(new String[]{"once","як бор"});
allWords.add(new String[]{"opinion","ақида"});
allWords.add(new String[]{"opportunity","имконият"});
allWords.add(new String[]{"order","фармоиш"});
allWords.add(new String[]{"outside","берун"});
allWords.add(new String[]{"own","худ"});
allWords.add(new String[]{"page","саҳифа"});
allWords.add(new String[]{"paint","ранг кардан"});
allWords.add(new String[]{"paper","коғаз"});
allWords.add(new String[]{"parent","падару модар"});
allWords.add(new String[]{"park","боғ"});
allWords.add(new String[]{"part","қисм"});
allWords.add(new String[]{"party","ҳизб"});
allWords.add(new String[]{"pass","гузаштан"});
allWords.add(new String[]{"past","гузашта"});
allWords.add(new String[]{"path","роҳ"});
allWords.add(new String[]{"
